### ISSUE TITLE
Stworzenie odpowiednich gałązek i przygotowanie ściągawki z gita

### ISSUE THREAD

**Issue by PawelBogdan** [Java2016-2017-grupa-1/MaplePlugin#1]

**Comment by Marcin-Chojnacki** [comment]
Ściągawka jest dostępna pod [linkiem](https://github.com/Java2016-2017-grupa-1/MaplePlugin/wiki/Git-basics-and-conventions).
Proszę o informację, czy coś należy zmienić/dodać.
Został też utworzony branch develop.

**Comment by PawelBogdan** [comment]
Jeżeli chodzi o mnie, ściągawka jest super:) Myślę, że możemy zamknąć ten issue.
